/**
 * scripts/generateTopo.ts
 *
 * Build-time script that runs the full terrain generation pipeline and writes
 * the resulting SVG path data to `data/topoPaths.ts` as a committed TypeScript
 * module. The component imports the pre-generated paths and renders them
 * without any runtime computation.
 *
 * Usage:
 *   npx tsx scripts/generateTopo.ts
 *   npm run generate:topo        (after adding the script to package.json)
 *
 * Re-run whenever you want to change the seed or terrain parameters.
 */

import { writeFileSync } from "fs"
import { resolve } from "path"
import { generateTerrain, DEFAULT_OPTIONS, type TopoPath } from "../lib/terrain/generateTerrain"

// ---------------------------------------------------------------------------
// Generation parameters
// Adjust these to change the terrain character and regenerate.
// ---------------------------------------------------------------------------

const PARAMS = {
  ...DEFAULT_OPTIONS,
  seed: 42,
  gridW: 80,
  gridH: 540,       // 540 rows × 10 − 700 offset = SVG y range −700…4700
  numLevels: 25,
  noiseScale: 55,
  octaves: 5,
  persistence: 0.5,
  lacunarity: 2.0,
  warpStrength: 18,
  minPathPoints: 10,
  chaikinIter: 2,
  scaleX: 10,       // 80 grid cols × 10 = 800 SVG units wide
  scaleY: 10,
  svgYOffset: -700, // shifts terrain up so it covers the hero viewport (viewBox y=−700…700)
}

// ---------------------------------------------------------------------------
// Run pipeline
// ---------------------------------------------------------------------------

console.log("Generating terrain heightmap…")
console.time("generate")
const paths: TopoPath[] = generateTerrain(PARAMS)
console.timeEnd("generate")
console.log(`Generated ${paths.length} contour paths.`)

// ---------------------------------------------------------------------------
// Serialise to TypeScript module
// ---------------------------------------------------------------------------

const header = `\
// AUTO-GENERATED by scripts/generateTopo.ts — do not edit manually.
// Seed: ${PARAMS.seed}  Grid: ${PARAMS.gridW}×${PARAMS.gridH}  Levels: ${PARAMS.numLevels}
// Re-generate: npm run generate:topo
`

// Serialise each path as a compact object literal on one line.
// The 'd' strings can be long but keeping them on one line keeps the file
// diff-friendly (one path per line) and avoids JSON escaping overhead.
const entries = paths
  .map((p) => `  { d: ${JSON.stringify(p.d)}, strokeOpacity: ${p.strokeOpacity} }`)
  .join(",\n")

const body = `\
export interface TopoPath {
  d: string
  strokeOpacity: number
}

export const TOPO_PATHS: TopoPath[] = [
${entries},
]
`

const output = header + "\n" + body
const outPath = resolve(__dirname, "../data/topoPaths.ts")

writeFileSync(outPath, output, "utf-8")
console.log(`Wrote ${(output.length / 1024).toFixed(1)} KB to data/topoPaths.ts`)
